import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

const poppins = Outfit({ weight: ['400','500','600','700','800','900'] ,subsets: ['latin'],});

export const metadata: Metadata = {
  title: "Yuvraj Verma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        
        {children}</body>
    </html>
  );
}
